version: '3.8'

services:
  server:
    build: ./server
    container_name: express-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://iamnajamal:LSPKhxLQMtqJ5KS3@cluster0.nehazya.mongodb.net/crudapp
    volumes:
      - ./server:/app
    command: node index.js

  client:
    build: ./client
    container_name: react-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
    command: npm run dev
